Added the :meth:`sys.exception` method which returns the active exception instance.