Bugfix: :func:`PyFunction_GetAnnotations` should return a borrowed
reference. It was returning a new reference.
